-- MySQL Script generated by MySQL Workbench
-- Mon Nov 26 12:11:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema walcarius
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `walcarius` DEFAULT CHARACTER SET utf8 ;
USE `walcarius` ;

-- -----------------------------------------------------
-- Table `walcarius`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `walcarius`.`categories` ;

CREATE TABLE IF NOT EXISTS `walcarius`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  `parentCategoryId` INT UNSIGNED NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `FK_CATEGORY_PARENT_CATEGORY_idx` (`parentCategoryId` ASC),
  CONSTRAINT `FK_CATEGORY_PARENT_CATEGORY`
    FOREIGN KEY (`parentCategoryId`)
    REFERENCES `walcarius`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walcarius`.`elementGroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `walcarius`.`elementGroups` ;

CREATE TABLE IF NOT EXISTS `walcarius`.`elementGroups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  `useClass` VARCHAR(100) NOT NULL,
  `categoryId` INT UNSIGNED NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ELEMENTGROUP_CATEGORY_idx` (`categoryId` ASC),
  CONSTRAINT `FK_ELEMENTGROUP_CATEGORY`
    FOREIGN KEY (`categoryId`)
    REFERENCES `walcarius`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walcarius`.`matters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `walcarius`.`matters` ;

CREATE TABLE IF NOT EXISTS `walcarius`.`matters` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `en1090Name` VARCHAR(60) NULL,
  `pricePerKg` FLOAT NOT NULL,
  `kgByLiter` FLOAT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walcarius`.`elements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `walcarius`.`elements` ;

CREATE TABLE IF NOT EXISTS `walcarius`.`elements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `elementGroupId` INT UNSIGNED NOT NULL,
  `matterId` INT UNSIGNED NOT NULL,
  `natureValues` JSON NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `FK_ELEMENT_ELEMENTGROUP_idx` (`elementGroupId` ASC),
  INDEX `FK_ELEMENT_MATTER_idx` (`matterId` ASC),
  CONSTRAINT `FK_ELEMENT_ELEMENTGROUP`
    FOREIGN KEY (`elementGroupId`)
    REFERENCES `walcarius`.`elementGroups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ELEMENT_MATTER`
    FOREIGN KEY (`matterId`)
    REFERENCES `walcarius`.`matters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walcarius`.`natures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `walcarius`.`natures` ;

CREATE TABLE IF NOT EXISTS `walcarius`.`natures` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `type` ENUM('STRING', 'INT', 'FLOAT', 'BOOLEAN') NOT NULL,
  `regex` VARCHAR(255) NULL,
  `min` FLOAT NULL,
  `max` FLOAT NULL,
  `nullable` TINYINT(1) NOT NULL DEFAULT 0,
  `redefine` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walcarius`.`elementGroupNatures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `walcarius`.`elementGroupNatures` ;

CREATE TABLE IF NOT EXISTS `walcarius`.`elementGroupNatures` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `elementGroupId` INT UNSIGNED NOT NULL,
  `natureId` INT UNSIGNED NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `FK_ELEMENTGROUPNATURE_ELEMENTGROUP_idx` (`elementGroupId` ASC),
  INDEX `FK_ELEMENTGROUPNATURE_NATURE_idx` (`natureId` ASC),
  CONSTRAINT `FK_ELEMENTGROUPNATURE_ELEMENTGROUP`
    FOREIGN KEY (`elementGroupId`)
    REFERENCES `walcarius`.`elementGroups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ELEMENTGROUPNATURE_NATURE`
    FOREIGN KEY (`natureId`)
    REFERENCES `walcarius`.`natures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walcarius`.`logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `walcarius`.`logins` ;

CREATE TABLE IF NOT EXISTS `walcarius`.`logins` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(50) NULL DEFAULT NULL,
  `lastname` VARCHAR(50) NULL DEFAULT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walcarius`.`actionGroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `walcarius`.`actionGroups` ;

CREATE TABLE IF NOT EXISTS `walcarius`.`actionGroups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `useClass` VARCHAR(100) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walcarius`.`elementGroupMatters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `walcarius`.`elementGroupMatters` ;

CREATE TABLE IF NOT EXISTS `walcarius`.`elementGroupMatters` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `elementGroupId` INT UNSIGNED NOT NULL,
  `matterId` INT UNSIGNED NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ELEMENTGROUP_MATTER_ELEMENTGROUP_idx` (`elementGroupId` ASC),
  INDEX `FK_ELEMENTGROUP_MATTER_MATTER_idx` (`matterId` ASC),
  CONSTRAINT `FK_ELEMENTGROUP_MATTER_ELEMENTGROUP`
    FOREIGN KEY (`elementGroupId`)
    REFERENCES `walcarius`.`elementGroups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ELEMENTGROUP_MATTER_MATTER`
    FOREIGN KEY (`matterId`)
    REFERENCES `walcarius`.`matters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walcarius`.`actionGroupParameters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `walcarius`.`actionGroupParameters` ;

CREATE TABLE IF NOT EXISTS `walcarius`.`actionGroupParameters` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `actionGroupId` INT UNSIGNED NOT NULL,
  `parameterId` INT UNSIGNED NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ACTIONPARAMETERS_ACTION_idx` (`actionGroupId` ASC),
  INDEX `FK_ACTIONPARAMETERS_NATURE_idx` (`parameterId` ASC),
  CONSTRAINT `FK_ACTIONGROUPPARAMETERS_ACTIONGROUP`
    FOREIGN KEY (`actionGroupId`)
    REFERENCES `walcarius`.`actionGroups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ACTIONGROUPPARAMETERS_NATURE`
    FOREIGN KEY (`parameterId`)
    REFERENCES `walcarius`.`natures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walcarius`.`actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `walcarius`.`actions` ;

CREATE TABLE IF NOT EXISTS `walcarius`.`actions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `actionGroupId` INT UNSIGNED NOT NULL,
  `matterId` INT UNSIGNED NULL,
  `natureValues` JSON NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ACTION_ACTIONGROUP_idx` (`actionGroupId` ASC),
  INDEX `FK_ACTION_MATTER_idx` (`matterId` ASC),
  CONSTRAINT `FK_ACTION_ACTIONGROUP`
    FOREIGN KEY (`actionGroupId`)
    REFERENCES `walcarius`.`actionGroups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ACTION_MATTER`
    FOREIGN KEY (`matterId`)
    REFERENCES `walcarius`.`matters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
