import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1782774212408 implements MigrationInterface {
    name = ' $npmConfigName1782774212408'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`priceRequestAdditionnalCosts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`type\` enum ('TRANSPORT_FEE', 'PACKAGING_FEE', 'CERTIFICATE_FEE', 'OTHER') NOT NULL DEFAULT 'OTHER', \`denomination\` varchar(200) NULL, \`quantity\` smallint NOT NULL, \`unit\` enum ('EURO', 'EURO_BY_UNIT') NOT NULL DEFAULT 'EURO', \`priceRequestId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplierOfferAdditionnalCosts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`price\` decimal NOT NULL, \`inputPrice\` decimal NOT NULL, \`denomination\` varchar(200) NULL, \`quantity\` smallint NOT NULL, \`unit\` enum ('EURO', 'EURO_BY_UNIT') NOT NULL DEFAULT 'EURO', \`supplierOfferId\` int NOT NULL, \`priceRequestAdditionnalCostId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplyListElements\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reference\` varchar(200) NULL, \`denomination\` varchar(200) NULL, \`matterReference\` varchar(50) NULL, \`quantity\` decimal NOT NULL, \`weight\` decimal NULL, \`format\` varchar(100) NOT NULL, \`isBlack\` tinyint NOT NULL, \`isBlasted\` tinyint NOT NULL, \`isPrimaryBlasted\` tinyint NOT NULL, \`length\` decimal NULL, \`width\` decimal NULL, \`thickness\` decimal NULL, \`quantityUnit\` varchar(20) NULL, \`remark\` varchar(200) NULL, \`supplyListId\` int NOT NULL, \`supplyCategoryId\` int NOT NULL, \`matterId\` int NOT NULL, \`elementId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplyLists\` (\`id\` int NOT NULL AUTO_INCREMENT, \`description\` varchar(100) NULL, \`model\` varchar(100) NULL, \`source\` varchar(10) NOT NULL, \`deliveryDate\` timestamp NULL, \`status\` varchar(15) NOT NULL, \`isAlreadyInBarset\` tinyint NOT NULL DEFAULT 0, \`projectId\` int NOT NULL, \`priceRequestId\` int NULL, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`projects\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reference\` varchar(30) NOT NULL, \`isEn1090\` tinyint NOT NULL DEFAULT 0, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`deletedAt\` timestamp NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchaseOrderElements\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` decimal NOT NULL, \`denomination\` varchar(200) NULL, \`status\` enum ('ATTENTE', 'ENCOURS', 'RECEPTIONNE') NOT NULL DEFAULT 'ATTENTE', \`isEn1090\` tinyint NOT NULL DEFAULT 0, \`isBlack\` tinyint NOT NULL DEFAULT 0, \`isBlasted\` tinyint NOT NULL DEFAULT 0, \`isPrimaryBlasted\` tinyint NOT NULL DEFAULT 0, \`format\` varchar(20) NULL, \`weight\` decimal NULL, \`matterReference\` varchar(20) NULL, \`quantityUnit\` varchar(20) NULL, \`thickness\` decimal NULL, \`length\` decimal NULL, \`width\` decimal NULL, \`remark\` varchar(200) NULL, \`deliveryDate\` timestamp NULL, \`realDeliveryDate\` timestamp NULL, \`price\` decimal NULL, \`unit\` enum ('EURO', 'EURO_BY_UNIT', 'EURO_BY_KG', 'EURO_BY_TON', 'EURO_BY_METER', 'EURO_BY_SQUARE_METER') NOT NULL DEFAULT 'EURO', \`isPrinted\` tinyint NOT NULL DEFAULT 0, \`printedQuantity\` smallint NOT NULL DEFAULT '0', \`purchaseOrderId\` int NOT NULL, \`supplierOfferElementId\` int NULL, \`supplyCategoryId\` int NULL, \`projectRef\` varchar(20) NULL, \`deletedAt\` timestamp NULL, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`scanPdf\` (\`id\` int NOT NULL AUTO_INCREMENT, \`purchaseOrderId\` int NOT NULL, \`name\` varchar(20) NOT NULL, \`url\` varchar(20) NOT NULL, \`comment\` text NULL, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`deletedAt\` timestamp NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchaseOrders\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reference\` varchar(20) NOT NULL, \`status\` enum ('CREATED', 'SENT', 'CANCELLED') NOT NULL DEFAULT 'CREATED', \`sendingDate\` timestamp NULL, \`remark\` text NULL, \`projectId\` int NULL, \`supplierId\` int NULL, \`supplierContactId\` int NULL, \`priceRequestId\` int NULL, \`loginId\` int NOT NULL, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`deletedAt\` timestamp NULL, \`internalRemark\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplierContacts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`firstname\` varchar(30) NULL, \`lastname\` varchar(30) NOT NULL, \`phone\` varchar(20) NULL, \`mail\` varchar(100) NULL, \`function\` varchar(100) NULL, \`isFavorite\` tinyint NOT NULL DEFAULT 0, \`language\` varchar(10) NOT NULL, \`supplierId\` int NOT NULL, \`deletedAt\` timestamp NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`suppliers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(10) NOT NULL, \`name\` varchar(100) NOT NULL, \`mail\` varchar(100) NULL, \`phone\` varchar(20) NULL, \`remark\` varchar(255) NULL, \`deletedAt\` timestamp NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplierOffers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reference\` varchar(20) NOT NULL, \`supplierReference\` varchar(50) NULL, \`remark\` varchar(200) NULL, \`isSent\` tinyint NOT NULL, \`sendingDate\` timestamp NULL, \`supplierId\` int NOT NULL, \`supplierContactId\` int NULL, \`priceRequestId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`barsetGenerations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`beamLength\` smallint NULL, \`beamOtherLengths\` json NULL, \`beamIsAutoCut\` tinyint NOT NULL DEFAULT 0, \`beamCutThreshold\` smallint NULL, \`beamMaxLoss\` smallint NULL, \`tubeLength\` smallint NULL, \`tubeOtherLengths\` json NULL, \`tubeIsAutoCut\` tinyint NOT NULL DEFAULT 0, \`tubeCutThreshold\` smallint NULL, \`tubeMaxLoss\` smallint NULL, \`generationDuration\` mediumint NULL, \`partsTotalLength\` int NULL, \`amalgamsTotalLength\` int NULL, \`partsQuantity\` mediumint NULL, \`amalgamsQuantity\` mediumint NULL, \`totalLoss\` int AS (\`amalgamsTotalLength\` - \`partsTotalLength\`) VIRTUAL NOT NULL, \`lossPercent\` decimal AS (((\`amalgamsTotalLength\` - \`partsTotalLength\`) / \`amalgamsTotalLength\`) * 100) VIRTUAL NOT NULL, \`priceRequestId\` int NOT NULL, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX \`REL_be7b42097e2b6f51935028f9f7\` (\`priceRequestId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`INSERT INTO \`walcarius\`.\`typeorm_metadata\`(\`database\`, \`schema\`, \`table\`, \`type\`, \`name\`, \`value\`) VALUES (DEFAULT, ?, ?, ?, ?, ?)`, ["walcarius","barsetGenerations","GENERATED_COLUMN","totalLoss","`amalgamsTotalLength` - `partsTotalLength`"]);
        await queryRunner.query(`INSERT INTO \`walcarius\`.\`typeorm_metadata\`(\`database\`, \`schema\`, \`table\`, \`type\`, \`name\`, \`value\`) VALUES (DEFAULT, ?, ?, ?, ?, ?)`, ["walcarius","barsetGenerations","GENERATED_COLUMN","lossPercent","((`amalgamsTotalLength` - `partsTotalLength`) / `amalgamsTotalLength`) * 100"]);
        await queryRunner.query(`CREATE TABLE \`priceRequests\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reference\` varchar(20) NOT NULL, \`remark\` text NULL, \`status\` enum ('CREATED', 'SENT', 'ORDERED', 'PARTIALLY') NOT NULL DEFAULT 'CREATED', \`isValidated\` tinyint NOT NULL DEFAULT 0, \`isDone\` tinyint NOT NULL DEFAULT 0, \`loginId\` int NOT NULL, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`deletedAt\` timestamp NULL, \`internalRemark\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`priceRequestElements\` (\`id\` int NOT NULL AUTO_INCREMENT, \`remark\` varchar(200) NULL, \`quantity\` decimal NOT NULL, \`weight\` decimal NULL, \`priceRequestId\` int NOT NULL, \`supplyListElementId\` int NULL, \`amalgamGroupId\` int NULL, \`unit\` enum ('EURO', 'EURO_BY_UNIT', 'EURO_BY_TON', 'EURO_BY_METER', 'EURO_BY_SQUARE_METER') NULL DEFAULT 'EURO_BY_UNIT', \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplierMatters\` (\`supplierId\` int NOT NULL, \`matterId\` int NOT NULL, PRIMARY KEY (\`supplierId\`, \`matterId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`smtpConfig\` (\`id\` int NOT NULL AUTO_INCREMENT, \`loginId\` int NOT NULL, \`username\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`host\` varchar(255) NULL, \`port\` int NOT NULL, \`active\` tinyint NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`quotes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`number\` varchar(50) NOT NULL, \`reference\` varchar(100) NULL, \`isEn1090\` tinyint NOT NULL, \`projectId\` int NULL, \`status\` int NULL DEFAULT '0', \`needSandblasting\` tinyint NULL DEFAULT 0, \`needMetallization\` tinyint NULL DEFAULT 0, \`needLacquering\` tinyint NULL DEFAULT 0, \`needPainting\` tinyint NULL DEFAULT 0, \`needGalvanization\` tinyint NULL DEFAULT 0, \`remarks\` text NULL, \`totalPrice\` decimal(10,2) NULL, \`elements\` json NULL, \`createdAt\` bigint NULL, \`updatedAt\` bigint NOT NULL, \`deletedAt\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`quote_projects\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`reference\` varchar(255) NOT NULL, \`customer\` varchar(255) NOT NULL, \`createdAt\` int NULL, \`updatedAt\` int NULL, \`deletedAt\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admission\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` int NOT NULL, \`date\` timestamp NULL, \`location\` varchar(255) NULL, \`admitedBy\` varchar(255) NULL, \`idElement\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`permission\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userGroup\` varchar(255) NOT NULL, \`category\` varchar(255) NOT NULL, \`read\` tinyint NOT NULL, \`write\` tinyint NOT NULL, \`delete\` tinyint NOT NULL, \`seePrices\` tinyint NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`elementGroupMatters\` (\`id\` int NOT NULL AUTO_INCREMENT, \`matterId\` int NOT NULL, \`elementGroupId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`elementGroupNatures\` (\`id\` int NOT NULL AUTO_INCREMENT, \`natureId\` int NOT NULL, \`elementGroupId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`actionGroupParameters\` (\`id\` int NOT NULL AUTO_INCREMENT, \`parameterId\` int NOT NULL, \`actionGroupId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`loginHistories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`fromIp\` varchar(45) NOT NULL, \`loginId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE INDEX \`IDX_e38ea1468b2190fc83e4c97681\` ON \`supplyCategoriesSuppliers\` (\`supplierId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_8966df5aa7e8e66080d7a263ef\` ON \`supplyCategoriesSuppliers\` (\`supplyCategoryId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d2a6f4831c9f1aedfc9db8a007\` ON \`supplierMatters\` (\`supplierId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_7b063d45ef813434bc1a504905\` ON \`supplierMatters\` (\`matterId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9bfef2bb6bd96fd3198147f5b1\` ON \`supplyCategoryNatures\` (\`supplyCategoryId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_2d622fac558c733bdc6c7daccc\` ON \`supplyCategoryNatures\` (\`natureId\`)`);
        await queryRunner.query(`ALTER TABLE \`actions\` ADD CONSTRAINT \`FK_0370fcf08839ceec5f01eb5af52\` FOREIGN KEY (\`actionGroupId\`) REFERENCES \`actionGroups\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`actions\` ADD CONSTRAINT \`FK_7a0da88f36dc2a17e51b7f2491d\` FOREIGN KEY (\`matterId\`) REFERENCES \`matters\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`priceRequestAdditionnalCosts\` ADD CONSTRAINT \`FK_800cf49d9ec741fae87acc579c3\` FOREIGN KEY (\`priceRequestId\`) REFERENCES \`priceRequests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplierOfferAdditionnalCosts\` ADD CONSTRAINT \`FK_760ce8cafee976fcf7579091c73\` FOREIGN KEY (\`supplierOfferId\`) REFERENCES \`supplierOffers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplierOfferAdditionnalCosts\` ADD CONSTRAINT \`FK_45da515e132995e4b8e84cc90e0\` FOREIGN KEY (\`priceRequestAdditionnalCostId\`) REFERENCES \`priceRequestAdditionnalCosts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`amalgams\` ADD CONSTRAINT \`FK_f4db8d19a7e14664fa7338312a5\` FOREIGN KEY (\`amalgamGroupId\`) REFERENCES \`amalgamGroups\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`amalgamParts\` ADD CONSTRAINT \`FK_5ab431883f035349b2638d3fcd8\` FOREIGN KEY (\`amalgamId\`) REFERENCES \`amalgams\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`amalgamParts\` ADD CONSTRAINT \`FK_d512162c9c453465545cba1a0f6\` FOREIGN KEY (\`supplyListElementId\`) REFERENCES \`supplyListElements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplyListElements\` ADD CONSTRAINT \`FK_6b74761163658b59cd25690d9ad\` FOREIGN KEY (\`supplyListId\`) REFERENCES \`supplyLists\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplyListElements\` ADD CONSTRAINT \`FK_7074dc365ec2d430e2c6aee7dc5\` FOREIGN KEY (\`supplyCategoryId\`) REFERENCES \`supplyCategories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplyListElements\` ADD CONSTRAINT \`FK_65a799422f073bfa4b228b72cbe\` FOREIGN KEY (\`elementId\`) REFERENCES \`elements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplyListElements\` ADD CONSTRAINT \`FK_beeabe833e18be2b881cbcdaee6\` FOREIGN KEY (\`matterId\`) REFERENCES \`matters\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplyLists\` ADD CONSTRAINT \`FK_7c0459870111d773c97de57b522\` FOREIGN KEY (\`projectId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplyLists\` ADD CONSTRAINT \`FK_f3dfc43fa5e45ac36e483583313\` FOREIGN KEY (\`priceRequestId\`) REFERENCES \`priceRequests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchaseOrderAdditionnalCosts\` ADD CONSTRAINT \`FK_9f51ce62db7efa03b16ed8f7699\` FOREIGN KEY (\`purchaseOrderId\`) REFERENCES \`purchaseOrders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`priceRequestElementOptions\` ADD CONSTRAINT \`FK_e85c73356f82007c311574007a5\` FOREIGN KEY (\`priceRequestElementId\`) REFERENCES \`priceRequestElements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplierOfferElementOptions\` ADD CONSTRAINT \`FK_1fb7a2255c0d586c9936ce8db3d\` FOREIGN KEY (\`supplierOfferElementId\`) REFERENCES \`supplierOfferElements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplierOfferElementOptions\` ADD CONSTRAINT \`FK_d1389729597cfeceb49f2237cd3\` FOREIGN KEY (\`priceRequestElementOptionId\`) REFERENCES \`priceRequestElementOptions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variantOptions\` ADD CONSTRAINT \`FK_fc382ca3e3a6dfd8d3b86be491b\` FOREIGN KEY (\`variantId\`) REFERENCES \`variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variants\` ADD CONSTRAINT \`FK_50adc26908f7e283aa715b66008\` FOREIGN KEY (\`supplyCategoryId\`) REFERENCES \`supplyCategories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variants\` ADD CONSTRAINT \`FK_6b77cf941ab5a1a14c9c0aeef88\` FOREIGN KEY (\`elementId\`) REFERENCES \`elements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variants\` ADD CONSTRAINT \`FK_e4b228d0e3fb84ea21cb03448e4\` FOREIGN KEY (\`matterId\`) REFERENCES \`matters\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplierOfferElements\` ADD CONSTRAINT \`FK_07cf7f19f62aea7a9fc16139825\` FOREIGN KEY (\`supplierOfferId\`) REFERENCES \`supplierOffers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplierOfferElements\` ADD CONSTRAINT \`FK_ae36ea3753e1a89da0f2d1c51eb\` FOREIGN KEY (\`priceRequestElementId\`) REFERENCES \`priceRequestElements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplierOfferElements\` ADD CONSTRAINT \`FK_3fe4216f4878a7c45d878054637\` FOREIGN KEY (\`variantId\`) REFERENCES \`variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchaseOrderElementOptions\` ADD CONSTRAINT \`FK_b1896fafb30c7d784f8c0233e4d\` FOREIGN KEY (\`purchaseOrderElementId\`) REFERENCES \`purchaseOrderElements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchaseOrderElements\` ADD CONSTRAINT \`FK_159c31fa7d0cc0221803c18ecca\` FOREIGN KEY (\`purchaseOrderId\`) REFERENCES \`purchaseOrders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchaseOrderElements\` ADD CONSTRAINT \`FK_fbd67b50f49776cafff63b0f9bb\` FOREIGN KEY (\`supplierOfferElementId\`) REFERENCES \`supplierOfferElements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchaseOrderElements\` ADD CONSTRAINT \`FK_0156927f17e94535a36435410b6\` FOREIGN KEY (\`supplyCategoryId\`) REFERENCES \`supplyCategories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`scanPdf\` ADD CONSTRAINT \`FK_aff08d5eee4becdd25e32620686\` FOREIGN KEY (\`purchaseOrderId\`) REFERENCES \`purchaseOrders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchaseOrders\` ADD CONSTRAINT \`FK_631f96d729c86ceed8c20e734f4\` FOREIGN KEY (\`projectId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchaseOrders\` ADD CONSTRAINT \`FK_e7a00d618a89788869a23ccb675\` FOREIGN KEY (\`supplierId\`) REFERENCES \`suppliers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchaseOrders\` ADD CONSTRAINT \`FK_8b909a57390cf632034f9999996\` FOREIGN KEY (\`supplierContactId\`) REFERENCES \`supplierContacts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchaseOrders\` ADD CONSTRAINT \`FK_9e1f280541e0bde30c94c7156f7\` FOREIGN KEY (\`priceRequestId\`) REFERENCES \`priceRequests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchaseOrders\` ADD CONSTRAINT \`FK_8679a0bf4f68fdb340e5e8712df\` FOREIGN KEY (\`loginId\`) REFERENCES \`logins\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplierContacts\` ADD CONSTRAINT \`FK_8fa466765ac23756b966cc01a09\` FOREIGN KEY (\`supplierId\`) REFERENCES \`suppliers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplierOffers\` ADD CONSTRAINT \`FK_72b5184252a421e4f15adf18c15\` FOREIGN KEY (\`supplierId\`) REFERENCES \`suppliers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplierOffers\` ADD CONSTRAINT \`FK_9d02a879b595a4bc29f1fb7c2ae\` FOREIGN KEY (\`supplierContactId\`) REFERENCES \`supplierContacts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplierOffers\` ADD CONSTRAINT \`FK_340475086b9a440bcaf5645910e\` FOREIGN KEY (\`priceRequestId\`) REFERENCES \`priceRequests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`barsetGenerations\` ADD CONSTRAINT \`FK_be7b42097e2b6f51935028f9f7b\` FOREIGN KEY (\`priceRequestId\`) REFERENCES \`priceRequests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`priceRequests\` ADD CONSTRAINT \`FK_8905864dc76eca394cbc8cb015a\` FOREIGN KEY (\`loginId\`) REFERENCES \`logins\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`priceRequestElements\` ADD CONSTRAINT \`FK_dac5a9c541398003e523f86fad5\` FOREIGN KEY (\`priceRequestId\`) REFERENCES \`priceRequests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`priceRequestElements\` ADD CONSTRAINT \`FK_658c6e8c2db5ed01bf95f9129f4\` FOREIGN KEY (\`supplyListElementId\`) REFERENCES \`supplyListElements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`priceRequestElements\` ADD CONSTRAINT \`FK_841b9c0698cb62e03381e83db21\` FOREIGN KEY (\`amalgamGroupId\`) REFERENCES \`amalgamGroups\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`amalgamGroups\` ADD CONSTRAINT \`FK_dfab69e05977ff5ee3e67b32106\` FOREIGN KEY (\`supplyCategoryId\`) REFERENCES \`supplyCategories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`amalgamGroups\` ADD CONSTRAINT \`FK_04056df85479c52b74a536fd2de\` FOREIGN KEY (\`matterId\`) REFERENCES \`matters\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`amalgamGroups\` ADD CONSTRAINT \`FK_e597ca849a24188b6bb801d63d0\` FOREIGN KEY (\`elementId\`) REFERENCES \`elements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`elements\` ADD CONSTRAINT \`FK_0065f8b495aa0bc71eb02ae509c\` FOREIGN KEY (\`elementGroupId\`) REFERENCES \`elementGroups\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`elements\` ADD CONSTRAINT \`FK_4ff49ba42171e7d0a068f2b35ec\` FOREIGN KEY (\`matterId\`) REFERENCES \`matters\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_ccde635bce518afe7c110858cc4\` FOREIGN KEY (\`parentCategoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`elementGroups\` ADD CONSTRAINT \`FK_593cbe717d6752c95e2aac9be61\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplyCategories\` ADD CONSTRAINT \`FK_99b096a6363f79eb28ac58012b5\` FOREIGN KEY (\`parentSupplyCategoryId\`) REFERENCES \`supplyCategories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplyCategories\` ADD CONSTRAINT \`FK_f7fd2ff4640047760b068dbc0a2\` FOREIGN KEY (\`elementGroupId\`) REFERENCES \`elementGroups\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplyCategoryNatures\` ADD CONSTRAINT \`FK_2d622fac558c733bdc6c7dacccd\` FOREIGN KEY (\`natureId\`) REFERENCES \`natures\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplyCategoryNatures\` ADD CONSTRAINT \`FK_9bfef2bb6bd96fd3198147f5b13\` FOREIGN KEY (\`supplyCategoryId\`) REFERENCES \`supplyCategories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplyCategoriesSuppliers\` ADD CONSTRAINT \`FK_e38ea1468b2190fc83e4c976814\` FOREIGN KEY (\`supplierId\`) REFERENCES \`suppliers\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`supplyCategoriesSuppliers\` ADD CONSTRAINT \`FK_8966df5aa7e8e66080d7a263ef3\` FOREIGN KEY (\`supplyCategoryId\`) REFERENCES \`supplyCategories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplierMatters\` ADD CONSTRAINT \`FK_d2a6f4831c9f1aedfc9db8a007f\` FOREIGN KEY (\`supplierId\`) REFERENCES \`suppliers\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`supplierMatters\` ADD CONSTRAINT \`FK_7b063d45ef813434bc1a504905c\` FOREIGN KEY (\`matterId\`) REFERENCES \`matters\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`supplierMatters\` DROP FOREIGN KEY \`FK_7b063d45ef813434bc1a504905c\``);
        await queryRunner.query(`ALTER TABLE \`supplierMatters\` DROP FOREIGN KEY \`FK_d2a6f4831c9f1aedfc9db8a007f\``);
        await queryRunner.query(`ALTER TABLE \`supplyCategoriesSuppliers\` DROP FOREIGN KEY \`FK_8966df5aa7e8e66080d7a263ef3\``);
        await queryRunner.query(`ALTER TABLE \`supplyCategoriesSuppliers\` DROP FOREIGN KEY \`FK_e38ea1468b2190fc83e4c976814\``);
        await queryRunner.query(`ALTER TABLE \`supplyCategoryNatures\` DROP FOREIGN KEY \`FK_9bfef2bb6bd96fd3198147f5b13\``);
        await queryRunner.query(`ALTER TABLE \`supplyCategoryNatures\` DROP FOREIGN KEY \`FK_2d622fac558c733bdc6c7dacccd\``);
        await queryRunner.query(`ALTER TABLE \`supplyCategories\` DROP FOREIGN KEY \`FK_f7fd2ff4640047760b068dbc0a2\``);
        await queryRunner.query(`ALTER TABLE \`supplyCategories\` DROP FOREIGN KEY \`FK_99b096a6363f79eb28ac58012b5\``);
        await queryRunner.query(`ALTER TABLE \`elementGroups\` DROP FOREIGN KEY \`FK_593cbe717d6752c95e2aac9be61\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_ccde635bce518afe7c110858cc4\``);
        await queryRunner.query(`ALTER TABLE \`elements\` DROP FOREIGN KEY \`FK_4ff49ba42171e7d0a068f2b35ec\``);
        await queryRunner.query(`ALTER TABLE \`elements\` DROP FOREIGN KEY \`FK_0065f8b495aa0bc71eb02ae509c\``);
        await queryRunner.query(`ALTER TABLE \`amalgamGroups\` DROP FOREIGN KEY \`FK_e597ca849a24188b6bb801d63d0\``);
        await queryRunner.query(`ALTER TABLE \`amalgamGroups\` DROP FOREIGN KEY \`FK_04056df85479c52b74a536fd2de\``);
        await queryRunner.query(`ALTER TABLE \`amalgamGroups\` DROP FOREIGN KEY \`FK_dfab69e05977ff5ee3e67b32106\``);
        await queryRunner.query(`ALTER TABLE \`priceRequestElements\` DROP FOREIGN KEY \`FK_841b9c0698cb62e03381e83db21\``);
        await queryRunner.query(`ALTER TABLE \`priceRequestElements\` DROP FOREIGN KEY \`FK_658c6e8c2db5ed01bf95f9129f4\``);
        await queryRunner.query(`ALTER TABLE \`priceRequestElements\` DROP FOREIGN KEY \`FK_dac5a9c541398003e523f86fad5\``);
        await queryRunner.query(`ALTER TABLE \`priceRequests\` DROP FOREIGN KEY \`FK_8905864dc76eca394cbc8cb015a\``);
        await queryRunner.query(`ALTER TABLE \`barsetGenerations\` DROP FOREIGN KEY \`FK_be7b42097e2b6f51935028f9f7b\``);
        await queryRunner.query(`ALTER TABLE \`supplierOffers\` DROP FOREIGN KEY \`FK_340475086b9a440bcaf5645910e\``);
        await queryRunner.query(`ALTER TABLE \`supplierOffers\` DROP FOREIGN KEY \`FK_9d02a879b595a4bc29f1fb7c2ae\``);
        await queryRunner.query(`ALTER TABLE \`supplierOffers\` DROP FOREIGN KEY \`FK_72b5184252a421e4f15adf18c15\``);
        await queryRunner.query(`ALTER TABLE \`supplierContacts\` DROP FOREIGN KEY \`FK_8fa466765ac23756b966cc01a09\``);
        await queryRunner.query(`ALTER TABLE \`purchaseOrders\` DROP FOREIGN KEY \`FK_8679a0bf4f68fdb340e5e8712df\``);
        await queryRunner.query(`ALTER TABLE \`purchaseOrders\` DROP FOREIGN KEY \`FK_9e1f280541e0bde30c94c7156f7\``);
        await queryRunner.query(`ALTER TABLE \`purchaseOrders\` DROP FOREIGN KEY \`FK_8b909a57390cf632034f9999996\``);
        await queryRunner.query(`ALTER TABLE \`purchaseOrders\` DROP FOREIGN KEY \`FK_e7a00d618a89788869a23ccb675\``);
        await queryRunner.query(`ALTER TABLE \`purchaseOrders\` DROP FOREIGN KEY \`FK_631f96d729c86ceed8c20e734f4\``);
        await queryRunner.query(`ALTER TABLE \`scanPdf\` DROP FOREIGN KEY \`FK_aff08d5eee4becdd25e32620686\``);
        await queryRunner.query(`ALTER TABLE \`purchaseOrderElements\` DROP FOREIGN KEY \`FK_0156927f17e94535a36435410b6\``);
        await queryRunner.query(`ALTER TABLE \`purchaseOrderElements\` DROP FOREIGN KEY \`FK_fbd67b50f49776cafff63b0f9bb\``);
        await queryRunner.query(`ALTER TABLE \`purchaseOrderElements\` DROP FOREIGN KEY \`FK_159c31fa7d0cc0221803c18ecca\``);
        await queryRunner.query(`ALTER TABLE \`purchaseOrderElementOptions\` DROP FOREIGN KEY \`FK_b1896fafb30c7d784f8c0233e4d\``);
        await queryRunner.query(`ALTER TABLE \`supplierOfferElements\` DROP FOREIGN KEY \`FK_3fe4216f4878a7c45d878054637\``);
        await queryRunner.query(`ALTER TABLE \`supplierOfferElements\` DROP FOREIGN KEY \`FK_ae36ea3753e1a89da0f2d1c51eb\``);
        await queryRunner.query(`ALTER TABLE \`supplierOfferElements\` DROP FOREIGN KEY \`FK_07cf7f19f62aea7a9fc16139825\``);
        await queryRunner.query(`ALTER TABLE \`variants\` DROP FOREIGN KEY \`FK_e4b228d0e3fb84ea21cb03448e4\``);
        await queryRunner.query(`ALTER TABLE \`variants\` DROP FOREIGN KEY \`FK_6b77cf941ab5a1a14c9c0aeef88\``);
        await queryRunner.query(`ALTER TABLE \`variants\` DROP FOREIGN KEY \`FK_50adc26908f7e283aa715b66008\``);
        await queryRunner.query(`ALTER TABLE \`variantOptions\` DROP FOREIGN KEY \`FK_fc382ca3e3a6dfd8d3b86be491b\``);
        await queryRunner.query(`ALTER TABLE \`supplierOfferElementOptions\` DROP FOREIGN KEY \`FK_d1389729597cfeceb49f2237cd3\``);
        await queryRunner.query(`ALTER TABLE \`supplierOfferElementOptions\` DROP FOREIGN KEY \`FK_1fb7a2255c0d586c9936ce8db3d\``);
        await queryRunner.query(`ALTER TABLE \`priceRequestElementOptions\` DROP FOREIGN KEY \`FK_e85c73356f82007c311574007a5\``);
        await queryRunner.query(`ALTER TABLE \`purchaseOrderAdditionnalCosts\` DROP FOREIGN KEY \`FK_9f51ce62db7efa03b16ed8f7699\``);
        await queryRunner.query(`ALTER TABLE \`supplyLists\` DROP FOREIGN KEY \`FK_f3dfc43fa5e45ac36e483583313\``);
        await queryRunner.query(`ALTER TABLE \`supplyLists\` DROP FOREIGN KEY \`FK_7c0459870111d773c97de57b522\``);
        await queryRunner.query(`ALTER TABLE \`supplyListElements\` DROP FOREIGN KEY \`FK_beeabe833e18be2b881cbcdaee6\``);
        await queryRunner.query(`ALTER TABLE \`supplyListElements\` DROP FOREIGN KEY \`FK_65a799422f073bfa4b228b72cbe\``);
        await queryRunner.query(`ALTER TABLE \`supplyListElements\` DROP FOREIGN KEY \`FK_7074dc365ec2d430e2c6aee7dc5\``);
        await queryRunner.query(`ALTER TABLE \`supplyListElements\` DROP FOREIGN KEY \`FK_6b74761163658b59cd25690d9ad\``);
        await queryRunner.query(`ALTER TABLE \`amalgamParts\` DROP FOREIGN KEY \`FK_d512162c9c453465545cba1a0f6\``);
        await queryRunner.query(`ALTER TABLE \`amalgamParts\` DROP FOREIGN KEY \`FK_5ab431883f035349b2638d3fcd8\``);
        await queryRunner.query(`ALTER TABLE \`amalgams\` DROP FOREIGN KEY \`FK_f4db8d19a7e14664fa7338312a5\``);
        await queryRunner.query(`ALTER TABLE \`supplierOfferAdditionnalCosts\` DROP FOREIGN KEY \`FK_45da515e132995e4b8e84cc90e0\``);
        await queryRunner.query(`ALTER TABLE \`supplierOfferAdditionnalCosts\` DROP FOREIGN KEY \`FK_760ce8cafee976fcf7579091c73\``);
        await queryRunner.query(`ALTER TABLE \`priceRequestAdditionnalCosts\` DROP FOREIGN KEY \`FK_800cf49d9ec741fae87acc579c3\``);
        await queryRunner.query(`ALTER TABLE \`actions\` DROP FOREIGN KEY \`FK_7a0da88f36dc2a17e51b7f2491d\``);
        await queryRunner.query(`ALTER TABLE \`actions\` DROP FOREIGN KEY \`FK_0370fcf08839ceec5f01eb5af52\``);
        await queryRunner.query(`DROP INDEX \`IDX_2d622fac558c733bdc6c7daccc\` ON \`supplyCategoryNatures\``);
        await queryRunner.query(`DROP INDEX \`IDX_9bfef2bb6bd96fd3198147f5b1\` ON \`supplyCategoryNatures\``);
        await queryRunner.query(`DROP INDEX \`IDX_7b063d45ef813434bc1a504905\` ON \`supplierMatters\``);
        await queryRunner.query(`DROP INDEX \`IDX_d2a6f4831c9f1aedfc9db8a007\` ON \`supplierMatters\``);
        await queryRunner.query(`DROP INDEX \`IDX_8966df5aa7e8e66080d7a263ef\` ON \`supplyCategoriesSuppliers\``);
        await queryRunner.query(`DROP INDEX \`IDX_e38ea1468b2190fc83e4c97681\` ON \`supplyCategoriesSuppliers\``);
        await queryRunner.query(`DROP TABLE \`loginHistories\``);
        await queryRunner.query(`DROP TABLE \`actionGroupParameters\``);
        await queryRunner.query(`DROP TABLE \`elementGroupNatures\``);
        await queryRunner.query(`DROP TABLE \`elementGroupMatters\``);
        await queryRunner.query(`DROP TABLE \`permission\``);
        await queryRunner.query(`DROP TABLE \`admission\``);
        await queryRunner.query(`DROP TABLE \`quote_projects\``);
        await queryRunner.query(`DROP TABLE \`quotes\``);
        await queryRunner.query(`DROP TABLE \`smtpConfig\``);
        await queryRunner.query(`DROP TABLE \`supplierMatters\``);
        await queryRunner.query(`DROP TABLE \`priceRequestElements\``);
        await queryRunner.query(`DROP TABLE \`priceRequests\``);
        await queryRunner.query(`DELETE FROM \`walcarius\`.\`typeorm_metadata\` WHERE \`type\` = ? AND \`name\` = ? AND \`schema\` = ? AND \`table\` = ?`, ["GENERATED_COLUMN","lossPercent","walcarius","barsetGenerations"]);
        await queryRunner.query(`DELETE FROM \`walcarius\`.\`typeorm_metadata\` WHERE \`type\` = ? AND \`name\` = ? AND \`schema\` = ? AND \`table\` = ?`, ["GENERATED_COLUMN","totalLoss","walcarius","barsetGenerations"]);
        await queryRunner.query(`DROP INDEX \`REL_be7b42097e2b6f51935028f9f7\` ON \`barsetGenerations\``);
        await queryRunner.query(`DROP TABLE \`barsetGenerations\``);
        await queryRunner.query(`DROP TABLE \`supplierOffers\``);
        await queryRunner.query(`DROP TABLE \`suppliers\``);
        await queryRunner.query(`DROP TABLE \`supplierContacts\``);
        await queryRunner.query(`DROP TABLE \`purchaseOrders\``);
        await queryRunner.query(`DROP TABLE \`scanPdf\``);
        await queryRunner.query(`DROP TABLE \`purchaseOrderElements\``);
        await queryRunner.query(`DROP TABLE \`projects\``);
        await queryRunner.query(`DROP TABLE \`supplyLists\``);
        await queryRunner.query(`DROP TABLE \`supplyListElements\``);
        await queryRunner.query(`DROP TABLE \`supplierOfferAdditionnalCosts\``);
        await queryRunner.query(`DROP TABLE \`priceRequestAdditionnalCosts\``);
    }

}
