export enum ERROR_MESSAGE {
    // 400
    BAD_REQUEST,
    NO_SUPPLIER_OFFER,
    PRICE_REQUEST_ALREADY_SENT,
    SUPPLIER_OFFER_NOT_EMPTY,
    NO_MAIL_FOR_SUPPLIER,
    INVALID_FILE,
    INVALID_FILE_FORMAT,
    PROJECT_HAS_ASSIGNED_SUPPLY_LIST,
    SUPPLY_LIST_ALREADY_ASSIGNED,
    SUPPLY_LIST_CONTAINS_SENT_ELEMENTS,
    SUPPLY_LIST_CONTAINS_ENCODED_PRICES,
    SUPPLY_LIST_IN_LOCKED_AMALGAMS,
    SUPPLY_LIST_NOT_IN_PRICE_REQUEST,
    NO_PURCHASE_ORDER_ELEMENT,
    PURCHASE_ORDER_ALREADY_SENT,
    NO_PURCHASE_ORDER,
    QUOTE_PROJECT_NOT_EMPTY,
    SUPPLIER_CODE_ALREADY_EXISTS,
    PURCHASE_ORDER_IS_CANCELLED,
    INVALID_ASKED_STICKER_FORMAT,
    PRICE_REQUEST_ALREADY_IN_PURCHASE_ORDER,
    INVALID_ELEMENTS_FOR_PURCHASE_ORDER,
    INVALID_ADD_COSTS_FOR_PURCHASE_ORDER,
    INVALID_AMALGAM_PARTS_QUANTITY,
    // 401
    UNAUTHORIZED,
    AUTHENTICATION_FAILED,
    INVALID_TOKEN,
    NO_USER_WITH_EMAIL,
    // 403
    FORBIDDEN,
    // 404
    NOT_FOUND,
    NO_FILE_FOUND,
    // 500
    INTERNAL_SERVER_ERROR,
    IMPOSSIBLE_FILE_MOVE,
    PDF_CONFIGURATION_NOT_FOUND,
    UNABLE_TO_ASSIGN_SUPPLY_LIST,
    UNABLE_TO_FREE_SUPPLY_LIST,
    UNABLE_TO_REGEN_AMALGAMS,
    // 501
    NOT_IMPLEMENTED,
    FOOTER_NOT_IMPLEMENTED,
    HEADER_NOT_IMPLEMENTED,
    // 600
    UNKNOWN_ERROR
}